# Generated by Django 3.0.4 on 2020-05-12 17:13

import bank.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('isCorporate', models.BooleanField(default=False)),
                ('physicalAddress', models.CharField(max_length=60)),
                ('postalAddress', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=30)),
                ('productbrand', models.CharField(max_length=30)),
                ('productModel', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
                ('description', ckeditor.fields.RichTextField()),
                ('image1', models.ImageField(upload_to=bank.models.product_image_uploader)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=bank.models.product_image_uploader)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=bank.models.product_image_uploader)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=bank.models.product_image_uploader)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationForm', models.FileField(blank=True, null=True, upload_to=bank.models.loan_application_uploader)),
                ('viewed', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
                ('applicationDate', models.DateTimeField(auto_now_add=True, verbose_name='dateApplied')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applicationDate'],
            },
        ),
        migrations.CreateModel(
            name='IndividualAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8)),
                ('firstName', models.CharField(max_length=60)),
                ('middleName', models.CharField(default='NIL', max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('isMale', models.BooleanField()),
                ('maidenName', models.CharField(max_length=60)),
                ('passportPhoto', models.ImageField(upload_to=bank.models.user_passportPhoto_uploader)),
                ('nationalID', models.CharField(max_length=60)),
                ('dob', models.CharField(max_length=60)),
                ('maritalStatus', models.CharField(max_length=60)),
                ('countryOfResidence', models.CharField(max_length=60)),
                ('Nationality', models.CharField(max_length=60)),
                ('passportNum', models.CharField(max_length=60)),
                ('passportIssuerCountry', models.CharField(max_length=60)),
                ('passportIssueDate', models.CharField(max_length=60)),
                ('passportExpiryDate', models.CharField(max_length=60)),
                ('yearsAtResidence', models.CharField(max_length=60)),
                ('residentialStatus', models.CharField(max_length=60)),
                ('sourceOfIncome', models.CharField(max_length=60)),
                ('workAddress', models.CharField(max_length=60)),
                ('workPhone', models.CharField(max_length=60)),
                ('workDesignation', models.CharField(max_length=60)),
                ('grossMonthlyIncome', models.CharField(max_length=60)),
                ('otherSourceOfIncome', models.CharField(max_length=60)),
                ('kin_fname', models.CharField(max_length=60)),
                ('kin_sname', models.CharField(max_length=60)),
                ('kin_phone', models.CharField(max_length=60)),
                ('kin_address', models.CharField(max_length=60)),
                ('kin_passportPhoto', models.ImageField(upload_to=bank.models.kin_passportPhoto_uploader)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalEntityName', models.CharField(max_length=60)),
                ('tradingAs', models.CharField(max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=bank.models.company_logo_uploader)),
                ('registrationNum', models.CharField(max_length=60, unique=True)),
                ('entityType', models.CharField(max_length=60)),
                ('industrySector', models.CharField(max_length=60)),
                ('dateOfReg', models.DateField(auto_now_add=True, verbose_name='date of registration')),
                ('countryOfReg', models.CharField(max_length=60)),
                ('contact1', models.CharField(max_length=60)),
                ('contact2', models.CharField(max_length=60)),
                ('website', models.CharField(max_length=60)),
                ('pOS', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=30)),
                ('productbrand', models.CharField(max_length=30)),
                ('productModel', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('image1', models.ImageField(upload_to=bank.models.product_image_uploader)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=bank.models.product_image_uploader)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=bank.models.product_image_uploader)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=bank.models.product_image_uploader)),
                ('claimer', models.CharField(max_length=30)),
                ('viewed', models.BooleanField(default=False)),
                ('dealStatus', models.CharField(choices=[('P', 'Pending'), ('S', 'Successful'), ('F', 'Failed')], max_length=30)),
                ('dealComment', ckeditor.fields.RichTextField()),
                ('claim_date', models.DateTimeField(verbose_name='date of claim')),
                ('claim_exp_date', models.DateTimeField(verbose_name='claim expiry date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnum', models.CharField(max_length=30, unique=True)),
                ('cardnum', models.CharField(max_length=30, unique=True)),
                ('acctype', models.CharField(max_length=30)),
                ('balance', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('cIF', models.CharField(max_length=30)),
                ('aTM', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
