# Generated by Django 3.0.6 on 2020-05-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
