# Generated by Django 3.0.6 on 2020-05-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_loanapplication_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='reference',
            field=models.CharField(default='826368188', max_length=30),
        ),
    ]
