# Generated by Django 3.0.7 on 2020-06-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_loanapplication_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='reference',
            field=models.CharField(default='684956233', max_length=30),
        ),
    ]
