# Generated by Django 3.0.7 on 2020-06-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20200611_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualaccount',
            name='maidenName',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='individualaccount',
            name='middleName',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='reference',
            field=models.CharField(default='518230922', max_length=30),
        ),
    ]
