# Generated by Django 3.0.7 on 2020-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20200611_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualaccount',
            name='maidenName',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='individualaccount',
            name='middleName',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='reference',
            field=models.CharField(default='662780614', max_length=30),
        ),
    ]
