# Generated by Django 3.0.7 on 2020-06-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20200611_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='reference',
            field=models.CharField(default='746230297', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
