# Generated by Django 3.0.7 on 2020-06-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20200611_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='reference',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='reference',
            field=models.CharField(default='331386196', max_length=30),
        ),
    ]
