# Generated by Django 3.0.7 on 2020-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20200611_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='reference',
            field=models.CharField(default='239705671', max_length=30),
        ),
    ]
