# Generated by Django 3.0.7 on 2020-06-11 21:54

import bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20200611_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='applicationForm',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='copyOfID',
            field=models.FileField(blank=True, null=True, upload_to=bank.models.loan_application_uploader),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='payslip',
            field=models.FileField(blank=True, null=True, upload_to=bank.models.loan_application_uploader),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='proofOfEmployment',
            field=models.FileField(blank=True, null=True, upload_to=bank.models.loan_application_uploader),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='proofOfResidence',
            field=models.FileField(blank=True, null=True, upload_to=bank.models.loan_application_uploader),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='reference',
            field=models.CharField(default='860765744', max_length=30),
        ),
    ]
